[package]
name = "my-23tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.7"
lexpr = "0.2.6"
proptest = "1.1.0"
sexp = "1.1.4"
sha2 = "0.10.6"
sise = "0.8.0"
