[package]
name = "recon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proptest = "1.1.0"
serde = { version = "1.0.162", features = ["derive"] }
sha2 = "0.10.6"
sise = "0.8.0"
